import { OUTFITS, CHARACTERS, STAGES, ENDINGS, CLUES, ROUTES, collectClue, chooseEnding, createGame, startEncounter, moveTo, stepGame, boost, useSkill, drainEvents, finishGame, getCollection, saveEnding } from './rules.js?v=53';
import { LanternScene } from './scene.js?v=53';
import { ENDING_EGGS } from './endings.js?v=53';
import { AudioDirector } from './audio.js?v=53';
const $=id=>document.getElementById(id), setText=(id,value)=>{if($(id).textContent!==String(value))$(id).textContent=String(value)};
let state=null,scene,loaded=false,paused=false,outfitId='jade',holding=false,autoGaze=false,moving=0,modalKind='',toastTimer,eggTimer,paradeLeft=0,before=[],sound=true,previousFocus,resultCountdown=0,cutsceneActive=false;
const keys=new Set(),labels=new Map(),audio=new AudioDirector();
const clueLabels=new Map();
function syncControlLayout(){document.body.classList.toggle('touch-controls',innerWidth<=960||Boolean(window.matchMedia?.('(pointer: coarse)').matches));}
syncControlLayout();window.addEventListener('resize',syncControlLayout);
const characterFor=n=>({...CHARACTERS.find(c=>c.id===n?.type),...(n?.name?{name:n.name,title:n.title}: {})});
function resetInputs(){holding=false;autoGaze=false;moving=0;keys.clear();$('auto-btn').setAttribute('aria-pressed','false');setText('auto-btn','♡ 持续放电');}
function toast(message){setText('toast',message);$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
function eggToast(message){setText('egg-toast',message);$('egg-toast').hidden=false;clearTimeout(eggTimer);eggTimer=setTimeout(()=>$('egg-toast').hidden=true,4200);}
function refreshCollection(){const c=getCollection();setText('book-count',`${c.endings.length}/${ENDINGS.length}`);}
OUTFITS.forEach((o,i)=>{const b=document.createElement('button');b.className='outfit-btn';b.dataset.outfit=o.id;b.style.setProperty('--outfit',o.color||['#a3c3b3','#e79585','#b3a4cf'][i]);b.innerHTML=`<i></i>${o.name}`;b.setAttribute('aria-label',`换装：${o.name}`);b.onclick=()=>choose(o.id,i);$('outfits').append(b);});
function choose(id,index){outfitId=id;const o=OUTFITS[index];document.querySelectorAll('.outfit-btn').forEach(b=>{b.classList.toggle('selected',b.dataset.outfit===id);b.setAttribute('aria-pressed',b.dataset.outfit===id?'true':'false')});setText('outfit-bonus',o.bonus||o.description||'');setText('outfit-caption',o.name);scene?.setOutfit(index);}
function rebuildTargets(){labels.clear();$('people').replaceChildren();for(const n of state.npcs){const c=characterFor(n),b=document.createElement('button');b.className='person-target';b.dataset.npc=n.id;b.setAttribute('aria-label',`邂逅${c.name}，${c.title}`);b.innerHTML=`<span class="person-heart">♡</span><span class="person-label"><small>${c.title}</small>${c.name}</span>`;
 b.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();if(!playable())return;pick(n.id);if(e.pointerType==='touch'||document.body.classList.contains('touch-controls')){autoGaze=Boolean(state.encounter||state.pendingNpc);holding=false;syncAuto();}else{holding=true;if(state.encounter?.hasRival)boost(state);}b.setPointerCapture(e.pointerId);});
 b.addEventListener('pointerup',()=>holding=false);b.addEventListener('pointercancel',()=>holding=false);b.addEventListener('click',e=>{if(e.detail===0){pick(n.id);autoGaze=true;syncAuto();}});labels.set(n.id,b);$('people').append(b);}}
function rebuildClues(){clueLabels.clear();$('clues').replaceChildren();for(const clue of state.clues){const b=document.createElement('button');b.className='clue-target';b.dataset.clue=clue.id;b.setAttribute('aria-label',`寻找线索：${clue.name}`);b.innerHTML=`<i>${clue.icon||'✧'}</i><span>${clue.name}</span>`;b.onclick=()=>{if(!playable())return;if(collectClue(state,clue.id)){resetInputs();toast(clue.id==='cat'?'把鱼丸捧好，慢慢靠近猫猫…':`去看看${clue.name}`);processEvents();}else toast(state.encounter?'先点地面离开争夺，再拾取信物':clue.hint);};clueLabels.set(clue.id,b);$('clues').append(b);}}
function routeBook(){if(!state)return;const found=state.clues.filter(c=>c.collected),visible=state.clues.filter(c=>c.unlocked&&!c.collected);const progress=(state.routeProgress||[]).filter(r=>r.completed>0).sort((a,b)=>b.completed/b.total-a.completed/a.total);showModal('routes',`<p class="modal-kicker">沿街拾珍 · 灯下寻缘</p><h2 id="modal-title">今夜的奇缘线索</h2><p>已找到 ${found.length} / ${CLUES.length} 件信物 · 时间已暂停</p><div class="token-tray">${found.map(c=>`<span>${c.icon||'✧'} ${c.name}</span>`).join('')||'留意街边发亮的小物件，点一下就会跑去查看。'}</div><div class="route-list">${visible.map(c=>`<div><b>${c.icon||'◇'} ${c.name}</b><small>${STAGES[c.stage].name} · ${c.hint}</small></div>`).join('')}</div>${progress.length?`<h3>缘分正在靠近</h3><div class="route-list">${progress.slice(0,8).map(p=>`<div><b>${p.eligible?'✓ 已可选择':`${p.completed} / ${p.total}`}</b><small>${p.eligible?ENDINGS.find(e=>e.id===p.endingId)?.title:p.nextHint||p.hint}</small></div>`).join('')}</div>`:''}<p class="collection-note">不是每一条路都要在同一夜走完。先选一段心仪的奇缘。</p><button class="primary" id="routes-done">记下了，继续逛灯会</button>`);$('routes-done').onclick=closeModal;}
$('route-btn').onclick=routeBook;
function playable(){return state?.phase==='playing'&&!paused&&!paradeLeft;}
async function startGame(){if(!loaded)return;await audio.unlock();audio.setEnabled(sound);cutsceneActive=false;resultCountdown=0;$('cutscene-controls').hidden=true;document.body.classList.remove('cutscene');closeModal();resetInputs();state=createGame(outfitId);before=getCollection().endings.slice();paused=false;paradeLeft=0;document.body.classList.add('game-playing');document.body.classList.remove('parading','duel','beauty-time');$('welcome').hidden=true;$('hud').hidden=false;$('play-ui').hidden=false;$('pause-btn').hidden=false;$('people').hidden=false;$('parade-caption').hidden=true;$('companions').replaceChildren();$('egg-toast').hidden=true;scene.reset(state);scene.setOutfit(OUTFITS.findIndex(o=>o.id===outfitId));rebuildTargets();rebuildClues();audio.start();audio.setStage(0);toast('点公子持续放电；情敌来了，点右侧争艳');updateHUD();}
function home(){cutsceneActive=false;resultCountdown=0;$('cutscene-controls').hidden=true;document.body.classList.remove('cutscene');closeModal();resetInputs();state=null;paused=false;paradeLeft=0;document.body.classList.remove('game-playing','parading','duel','beauty-time');for(const id of ['hud','play-ui','pause-btn','people','parade-caption','target-meter','scene-transition'])$(id).hidden=true;$('welcome').hidden=false;scene.setMode('welcome');scene.setOutfit(OUTFITS.findIndex(o=>o.id===outfitId));audio.stop();refreshCollection();}
function pick(id){if(!playable())return;const n=state.npcs.find(n=>n.id===id);if(!n||n.status==='won')return;if(state.encounter?.npcId===id)return;if(startEncounter(state,id)){autoGaze=false;syncAuto();processEvents();}else if(n.cooldown>0)toast('他还没缓过神来，先逛逛别处吧');}
function syncAuto(){$('auto-btn').setAttribute('aria-pressed',autoGaze?'true':'false');setText('auto-btn',autoGaze?'♡ 放电中 · 点停':'♡ 持续放电');}
function showModal(kind,html){previousFocus=document.activeElement;resetInputs();paused=true;audio.pause();modalKind=kind;$('modal-content').innerHTML=html;$('modal').hidden=false;$('modal-close').hidden=kind==='ending';requestAnimationFrame(()=>($('modal-content').querySelector('button')||$('modal-close')).focus());}
function closeModal(){if($('modal').hidden)return;$('modal').hidden=true;modalKind='';paused=false;resetInputs();if(state?.phase==='playing')audio.resume();previousFocus?.isConnected&&previousFocus.focus();}
function help(){showModal('help',`<p class="modal-kicker">良 宵 游 玩 指 南</p><h2 id="modal-title">心动，要眼疾手快</h2><div class="help-list"><div><b>壹</b><p><strong>快速跑动，三街寻缘</strong><br>按住左右箭头或 A / D 快跑，也可点地面跑过去。走过街口就换景，灯市、寺前与幽园可以往返。</p></div><div><b>贰</b><p><strong>点人放电，左右分工</strong><br>手机点公子便会走近并持续放电，左侧按钮可暂停；右侧大按钮专管「连点争艳」，不必双手同时按住。横竖屏自动换位，电脑也可长按公子、反复按空格。书生与卖油郎一位情敌，医师与商家两位，侠客与奇人三位，状元与世家四位，王侯与太子五位，微服天子六位。</p></div><div><b>叁</b><p><strong>八秒倾城，放手一搏</strong><br>连续结缘三次会自动开启八秒倾城，放电更快、心动值翻倍。每局三次「回眸一笑」可打断情敌。移动会中断放电。</p></div><div><b>肆</b><p><strong>上元散场，奇缘开卷</strong><br>一百五十秒内，在三街邂逅十四类公子。点街边的小信物，解开状元、东宫与微服天子的隐藏线。先买鱼丸，再去幽园找猫。收灯后，亲自选择已开启的归宿，观看专属过场与彩蛋。</p></div></div><button class="primary" id="help-done">记住了，去看花灯 →</button>`);$('help-done').onclick=closeModal;}
function book(){const c=getCollection();showModal('book',`<p class="modal-kicker">每 一 次 相 逢 都 有 回 响</p><h2 id="modal-title">你的缘分簿</h2><p>已珍藏 ${c.endings.length} / ${ENDINGS.length} 段上元故事 · 最高心动 ${c.best}</p><div class="collection-grid">${ENDINGS.map(e=>{const got=c.endings.includes(e.id);return `<div class="ending-card ${got?'':'locked'}"><span>${got?'✧':'◇'}</span><strong>${got?e.title:'未完的故事'}</strong><small>${got?(e.subtitle||'良宵已珍藏'):(e.hint||'试试与不同公子结缘')}</small></div>`}).join('')}</div>${c.legacyEndings.length?`<p class="legacy-note">初见篇的 ${c.legacyEndings.length} 个旧结局，仍为你保留。</p>`:''}<p class="collection-note">收藏仅保存在当前浏览器；不跨设备同步，清除网站数据会清除收藏。</p>`);}
function pauseGame(){if(!playable())return;showModal('pause',`<p class="modal-kicker">灯 火 为 你 稍 候</p><h2 id="modal-title">歇一歇，再逛逛</h2><p>良宵还剩 ${Math.ceil(state.timeLeft)} 秒。<br>你的心动与脚步，都停在这里。</p><button class="primary" id="resume-btn">继续逛灯市 →</button><button class="secondary" id="finish-btn">提前归家 · 看我的结局</button><button class="secondary" id="wardrobe-btn">重新选装，再赴灯会</button>`);$('resume-btn').onclick=closeModal;$('finish-btn').onclick=()=>{closeModal();finishGame(state);processEvents();};$('wardrobe-btn').onclick=home;}
function endingEgg(){if(state.wins.length===12)return{title:'彩蛋 · 明年请早',text:state.endingEgg?.text||'掌柜看着长长的队伍，默默挂出一块牌子：明年请早。'};const types=new Set(state.wins.map(id=>state.npcs.find(n=>n.id===id)?.type));if(types.size<8&&types.has('visitor')&&types.has('ghost'))return{title:'彩蛋 · 一船装下人间与月光',text:state.endingEgg?.text||'异乡旅人拿出一颗夜明珠，幽魂却从珠中掏出一碗热汤圆。你笑着把两个人一起拉上了画舫。'};if(types.size===8)return{title:'彩蛋 · 汴京第一醋坊',text:'八位公子齐齐送来一盏心灯。书生写诗，侠客拔剑，医者递上清火茶。你把灯一一挂好，宣布：「诸位，先猜灯谜，答对的替我买汤圆。」整条御街笑成了花。'};if(types.has('ghost'))return{title:'彩蛋 · 原来你也怕黑',text:'幽魂替你照了一路的灯。走进暗巷，他忽然攥住你的衣袖：「姑娘……能不能把灯再点亮一点？」原来，鬼也会怕黑。'};if(types.has('visitor'))return{title:'彩蛋 · 波斯语的秘密',text:'异乡旅人教你一句祝福，说是「元宵快乐」。卖汤圆的大娘却笑了：「姑娘，他那句分明是——明年也想和你来。」'};const c=CHARACTERS.find(c=>types.has(c.id));return {title:'彩蛋 · 灯下留笺',text:c?.egg||'他偷偷把最圆的一颗汤圆留给了你，又怕心意太明显，连碗也一起推了过来。'};}
function showEnding(auto=false){const e=state.ending||ENDINGS[0];cutsceneActive=false;resultCountdown=0;$('cutscene-controls').hidden=true;document.body.classList.remove('parading','cutscene');$('parade-caption').hidden=true;scene.setMode('results');refreshCollection();const n=state.wins.length,confirmed=state.endingConfirmed;showModal('ending',`<p class="modal-kicker">上元收灯 · 良宵入梦</p><h2 id="modal-title">${confirmed?e.title:'今夜，你愿意走向哪一段故事？'}</h2><div class="result-stats"><div><strong>${state.score}</strong><small>心动值</small></div><div><strong>${n}</strong><small>公子倾心</small></div><div><strong>${state.tokens.length}</strong><small>奇缘信物</small></div></div>${confirmed?`<span class="new-ending">${before.includes(e.id)?'再次相逢':'新结局已珍藏'}</span><p class="ending-story">${e.text}</p><p class="ending-story egg-story">${ENDING_EGGS[e.scene]?.text||''}</p>`:`<p class="result-note">沿途的相逢与信物，开启了 ${(state.availableEndings||[]).length} 种归宿。<br>选定一条，写下属于你的结局。</p><div class="ending-choices">${(state.availableEndings||[e]).map(v=>`<button class="ending-choice ${v.id===e.id?'selected':''}" data-ending="${v.id}" aria-pressed="${v.id===e.id}"><span class="choice-symbol">${({solo:'月',cat:'喵',empress:'凤',consort:'花',champion:'魁',crownPrincess:'鸾',princess:'禧',heiress:'缘'})[v.scene]||'缘'}</span><strong>${v.title}</strong><small>${v.subtitle}</small></button>`).join('')}</div><p id="ending-preview" class="ending-preview">${e.text}</p>`}<button class="primary" id="cinema-btn">${confirmed?'重看专属结局':'就选这段奇缘 · 看结局'} →</button><button class="secondary" id="again-btn">换身衣裳，再赴灯会</button><button class="text-btn" id="result-book-btn">翻开缘分簿</button>`);for(const b of $('modal-content').querySelectorAll('[data-ending]'))b.onclick=()=>{const id=b.dataset.ending;if(!chooseEnding(state,id))return;for(const v of $('modal-content').querySelectorAll('[data-ending]')){v.classList.toggle('selected',v===b);v.setAttribute('aria-pressed',v===b?'true':'false');}setText('ending-preview',state.ending.text);};$('cinema-btn').onclick=startCutscene;$('again-btn').onclick=home;$('result-book-btn').onclick=book;audio.stop();audio.cue('scoreboard');}
function startCutscene(){if(!state.endingConfirmed){chooseEnding(state,state.ending.id);saveEnding(state);state.endingConfirmed=true;refreshCollection();}resultCountdown=0;cutsceneActive=true;closeModal();paused=false;resetInputs();for(const id of ['hud','play-ui','people','pause-btn','scene-transition'])$(id).hidden=true;document.body.classList.remove('parading','changing-stage');document.body.classList.add('cutscene');$('cutscene-controls').hidden=false;scene.setMode('cutscene');audio.stop();audio.startEnding(scene.endingType(state));}
$('cutscene-replay').onclick=startCutscene;$('cutscene-again').onclick=home;$('cutscene-result').onclick=()=>{audio.stop();showEnding(false);};
function processEvents(){const events=drainEvents(state);scene.consume(events,state);for(const e of events){
 if(e.type==='encounter'){const c=characterFor(state.npcs.find(n=>n.id===(e.npcId||state.encounter?.npcId)));if(c)toast(`${c.name} · ${document.body.classList.contains('touch-controls')?'持续放电中，右侧连点争艳':'长按放电，传递心意'}`);audio.cue('zap');}
 else if(e.type==='rivalWarning'){toast(`${e.rivalName}正往这边来…`);audio.cue('tick');}
 else if(e.type==='clue'){toast(e.text||'奇缘信物已收好');audio.cue('gate');}
 else if(e.type==='unlock'){toast(e.text||`${e.name}出现在${STAGES[e.stage].name}`);rebuildTargets();audio.cue('beauty');}
 else if(e.type==='rival'){toast(`${e.rivalName||'情敌'}来了！连点争艳，抢先一步`);audio.cue('tick');}
 else if(e.type==='win'){holding=false;autoGaze=false;syncAuto();const n=state.npcs.find(n=>n.id===e.npcId),c=characterFor(n);toast(`${c?.name||'公子'}倾心相随 · 心动 +${e.earned||e.score||0}`);const chip=document.createElement('span');chip.className='companion-chip';chip.textContent=`♡ ${c?.name||'良缘'}`;$('companions').append(chip);audio.cue('win');}
 else if(e.type==='lose'){resetInputs();toast(e.text||'慢了一步！缓缓神，再寻一段缘');audio.cue('lose');}
 else if(e.type==='stage'){setText('transition-title',STAGES[state.stage].name);audio.setStage(state.stage);audio.cue('gate');}
 else if(e.type==='beauty'){toast('倾城时刻！八秒放电加速，心动翻倍');audio.cue('beauty');}
 else if(e.type==='egg'){const c=CHARACTERS.find(c=>c.id===(e.charId||e.characterId||e.character));eggToast(e.text||e.message||c?.egg||'✧ 一段奇缘，已写入今夜的故事');}
 else if(e.type==='skill'){toast('回眸一笑 · 情敌心乱了');audio.cue('zap');}
 else if(e.type==='end'){resetInputs();clearTimeout(toastTimer);clearTimeout(eggTimer);$('toast').classList.remove('show');$('egg-toast').hidden=true;audio.stop();audio.cue('win');$('encounter').hidden=true;$('target-meter').hidden=true;$('pause-btn').hidden=true;if(state.wins.length){paradeLeft=Math.min(7,3+state.wins.length*.30);scene.setMode('parade');document.body.classList.add('parading');$('parade-caption').hidden=false;}else showEnding(true);}
}}
function skill(){if(!playable())return;if(useSkill(state)){processEvents();}else toast(state.skillCharges?'先点一位公子，再回眸一笑':'今夜三次回眸已用完');}
function updateHUD(){if(!state)return;const transition=state.transitionLeft>0;$('scene-transition').hidden=!transition;document.body.classList.toggle('changing-stage',transition);if(transition){const elapsed=.8-state.transitionLeft;$('scene-transition').style.opacity=Math.min(1,elapsed/.26,state.transitionLeft/.3);} const s=Math.ceil(state.timeLeft);setText('timer',`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`);$('timer').classList.toggle('urgent',s<=20);$('timer-fill').style.width=`${state.timeLeft/(state.duration||150)*100}%`;setText('score',state.score);setText('wins',state.wins.length);setText('skill-count',`可用 ${state.skillCharges} 次 · E`);$('skill-btn').disabled=state.skillCharges<=0;setText('location-name',STAGES[state.stage].name);setText('stage-count',`${['壹','贰','叁'][state.stage]} / 叁`);$('street-dot').style.left=`${state.stage*33.3+(state.hero.x/26)*33.3}%`;$('left-exit').querySelector('small').textContent=STAGES[(state.stage+2)%3].name.slice(-2);$('right-exit').querySelector('small').textContent=STAGES[(state.stage+1)%3].name.slice(-2);
 const beauty=state.beautyLeft>0;document.body.classList.toggle('beauty-time',beauty);setText('energy-title',beauty?'倾城时刻 ✧':'倾城时刻');setText('energy-count',beauty?`${Math.ceil(state.beautyLeft)}秒`:`${Math.floor(state.energy)}%`);setText('energy-note',beauty?'放电加速 · 心动翻倍':'连结三缘，八秒倾城');$('energy-fill').style.width=`${beauty?state.beautyLeft/8*100:state.energy}%`;
 const e=state.encounter;$('encounter').hidden=(!e&&!state.pendingNpc)||!!paradeLeft||state.phase!=='playing';$('play-hint').hidden=!!e||!!state.pendingNpc;document.body.classList.toggle('duel',!!e?.hasRival);$('boost-btn').disabled=!e?.hasRival&&!beauty;$('target-meter').hidden=!e||!!paradeLeft;
 if(e){setText('rival-count',`${e.rivals?.filter(r=>r.active).length||0} / ${e.rivals?.length||0} 位情敌`);$('your-progress').style.width=`${e.progress}%`;$('rival-progress').style.width=`${e.hasRival?Math.min(e.rivalProgress,100-e.progress):0}%`;setText('meter-title',e.hasRival?'♡ 连点争艳':'♡ 一眼倾心');setText('meter-percent',`${Math.floor(e.progress)}%`);setText('encounter-status',e.hasRival?(e.freezeLeft>0?'情敌失神中 · 快！':`${e.rivals?.filter(r=>r.active).length||1} 位情敌 · 连点！`):(holding||autoGaze?'心动正在升温…':'点左侧，继续放电'));}
 setText('clue-count',`${state.tokens.length}/${CLUES.length}`);for(const [id,b]of clueLabels){const clue=state.clues.find(c=>c.id===id),x=(clue.x*90-scene.cameraX)/scene.W*scene.width;b.hidden=!!e||clue.stage!==state.stage||!clue.unlocked||clue.collected||!!paradeLeft||state.phase!=='playing'||x<28||x>scene.width-28;b.style.left=`${x}px`;b.style.top=`${Math.min((scene.ground+20)/scene.H*scene.height,scene.height-110)}px`;b.classList.toggle('seeking',state.pendingClue===id);}
 const positions=scene.positions(state);for(const [id,b]of labels){const p=positions.find(p=>p.id===id);b.hidden=!p?.visible||!!paradeLeft||state.npcs.find(n=>n.id===id)?.status==='locked';if(!p)continue;const n=state.npcs.find(n=>n.id===id);b.style.left=`${p.x}px`;b.style.top=`${p.y}px`;b.style.width=`${p.width}px`;b.style.height=`${p.height}px`;b.classList.toggle('active',e?.npcId===id);b.classList.toggle('cooling',n.cooldown>0);b.querySelector('.person-heart').textContent=n.cooldown>0?`${Math.ceil(n.cooldown)}s`:'♡';if(e?.npcId===id){$('target-meter').style.left=`${Math.max(75,Math.min(innerWidth-75,p.x))}px`;$('target-meter').style.top=`${Math.max(innerWidth/innerHeight>1?110:220,p.y-p.height-7)}px`;}}
 if(playable())audio.setIntensity(s<=20?2:e?.hasRival?1:0);
}
$('start-btn').onclick=startGame;$('help-btn').onclick=help;$('book-btn').onclick=book;$('pause-btn').onclick=pauseGame;$('skill-btn').onclick=skill;$('audio-btn').onclick=async()=>{sound=!sound;if(sound){await audio.unlock();audio.setEnabled(true);if(state?.phase==='playing'&&!paused)audio.start();}else audio.setEnabled(false);$('audio-btn').classList.toggle('audio-on',sound);$('audio-btn').setAttribute('aria-label',sound?'关闭乐声':'开启乐声');$('audio-btn').title=sound?'关闭乐声':'开启乐声';if(sound&&cutsceneActive)audio.startEnding(scene.endingType(state),scene.modeAge);};
function tapBoost(){if(playable())boost(state);}
$('boost-btn').addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();tapBoost();});$('boost-btn').onclick=e=>{if(!e||e.detail===0)tapBoost();};$('auto-btn').onclick=()=>{if(!playable())return;autoGaze=!autoGaze;syncAuto();};
$('gaze-btn').addEventListener('pointerdown',e=>{if(!playable())return;e.preventDefault();holding=true;$('gaze-btn').setPointerCapture(e.pointerId)});for(const name of ['pointerup','pointercancel'])$('gaze-btn').addEventListener(name,()=>holding=false);
for(const [id,dir]of[['move-left',-1],['move-right',1]]){let down=0;$(id).addEventListener('pointerdown',e=>{if(!playable())return;e.preventDefault();down=performance.now();moving=dir;holding=autoGaze=false;syncAuto();$(id).setPointerCapture(e.pointerId)});$(id).addEventListener('pointerup',()=>{moving=0;if(playable()&&performance.now()-down<200)moveTo(state,state.hero.x+dir*3);});$(id).addEventListener('pointercancel',()=>moving=0);$(id).addEventListener('click',e=>{if(e.detail===0&&playable())moveTo(state,state.hero.x+dir*3);});}
$('modal-close').onclick=()=>state?.phase==='ended'?showEnding():closeModal();$('modal').querySelector('.modal-backdrop').onclick=()=>{if(modalKind!=='ending'){if(state?.phase==='ended')showEnding();else closeModal();}};document.querySelector('.brand').onclick=e=>{e.preventDefault();if(playable())pauseGame();else if(!paradeLeft)home();};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modalKind==='ending')return;if(!$('modal').hidden){if(state?.phase==='ended')showEnding();else closeModal();}else pauseGame();return;}if(!playable())return;const key=e.key.toLowerCase();if(['arrowleft','arrowright','a','d',' ','e'].includes(key))e.preventDefault();keys.add(key);if(e.code==='Space'&&!e.repeat)boost(state);if(key==='e'&&!e.repeat)skill();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{if(playable())pauseGame();resetInputs();});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(playable())pauseGame();else if(paradeLeft||cutsceneActive){paused=true;audio.pause();}}else if(paradeLeft||cutsceneActive){paused=false;audio.resume();}});
$('modal').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const fs=[...$('modal').querySelectorAll('button:not([hidden])')].filter(b=>b.offsetParent!==null);if(e.shiftKey&&document.activeElement===fs[0]){e.preventDefault();fs.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===fs.at(-1)){e.preventDefault();fs[0]?.focus();}});
let last=performance.now(),accumulator=0;
function frame(now){if(state?.events.length)processEvents();const dt=Math.min((now-last)/1000,.1);last=now;if(playable()){accumulator+=dt;const move=moving||(keys.has('arrowright')||keys.has('d')?1:keys.has('arrowleft')||keys.has('a')?-1:0);if(move){holding=autoGaze=false;syncAuto();}while(accumulator>=1/60&&playable()){stepGame(state,1/60,{move,holding:holding||autoGaze});accumulator-=1/60;processEvents();}}else accumulator=0;
 if(paradeLeft&&!paused){paradeLeft-=dt;if(paradeLeft<=0){paradeLeft=0;showEnding(true);}}
 if(resultCountdown>0&&modalKind==='ending'&&!document.hidden){resultCountdown=Math.max(0,resultCountdown-dt);setText('result-countdown',`${Math.ceil(resultCountdown)} 秒后，花灯台开场…`);if(resultCountdown<=0)startCutscene();}if(cutsceneActive&&scene.modeAge<12&&scene.modeAge+dt>=12)audio.cue('punch');scene.endingBeat=audio.getBeat()?.beat;scene.update(paused?0:dt,state,playable()&&(holding||autoGaze));if(state&&!cutsceneActive)updateHUD();requestAnimationFrame(frame);}
choose('jade',0);refreshCollection();try{scene=new LanternScene($('world'),CHARACTERS);await scene.load();if(document.fonts)await document.fonts.load('16px LanternKai');loaded=true;choose(outfitId,0);$('start-btn').disabled=false;$('start-btn').innerHTML='开始逛灯会 <span>→</span>';scene.renderer.domElement.addEventListener('pointerdown',e=>{if(!playable())return;const rect=$('world').getBoundingClientRect();if(e.clientY-rect.top<rect.height*.35)return;moveTo(state,(scene.cameraX+(e.clientX-rect.left)/rect.width*scene.W)/90);holding=autoGaze=false;syncAuto();});requestAnimationFrame(frame);}catch(err){console.error('灯市加载失败',err);$('load-error').hidden=false;}

$('audio-btn').classList.add('audio-on');$('audio-btn').setAttribute('aria-label','关闭乐声');$('audio-btn').title='关闭乐声';
